# Generated by Django 2.2.4 on 2019-11-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0003_auto_20191107_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_of_user',
        ),
    ]
