# Generated by Django 2.2.4 on 2019-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='  ', help_text='Контакты для связи', max_length=256, verbose_name='Телефон, vk или telegram'),
        ),
    ]
