# Generated by Django 2.2.4 on 2019-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_profile'),
        ('account', '0007_auto_20191116_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='knowledge',
            field=models.ManyToManyField(blank=True, help_text='Курсы, которые Вы можете преподавать', null=True, related_name='Profile_knowledge', to='core.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='studying',
            field=models.ManyToManyField(blank=True, help_text='Курсы, которые Вы уже изучаете', null=True, related_name='Profile_studying', to='core.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teaching',
            field=models.ManyToManyField(blank=True, help_text='Курсы, которые Вы уже преподаёте', null=True, related_name='Profile_teaching', to='core.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishes',
            field=models.ManyToManyField(blank=True, help_text='Курсы, которые Вы хотите изучать', null=True, related_name='Profile_wishes', to='core.Course'),
        ),
    ]
