# Generated by Django 2.2.4 on 2019-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191116_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='uni/account/static/images/default.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
