# Generated by Django 2.2.4 on 2019-11-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191122_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='uni/account/static/images/default.png', upload_to='users/%user.pk'),
        ),
    ]
