# Generated by Django 2.2.4 on 2019-08-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Место проведения', max_length=256, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название курса', max_length=256, verbose_name='Название курса')),
                ('status', models.CharField(choices=[('started', 'Запущен'), ('in_progress', 'В процессе'), ('search', 'Набор')], max_length=16)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
            ],
        ),
    ]
