# Generated by Django 2.2.4 on 2019-08-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190810_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Староста не найден(а)', help_text='Ответственный за курс', max_length=128, verbose_name='Староста курса')),
                ('telephone', models.CharField(default='Староста не найден(а)', help_text='Номер для связи', max_length=64, verbose_name='Номер телефона')),
                ('vk_id', models.CharField(blank=True, help_text='вк дл связи', max_length=64, null=True, verbose_name='Vk.id')),
                ('email', models.CharField(blank=True, help_text='Адрес электронной почты для связи', max_length=64, null=True, verbose_name='email address')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='group_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.President'),
        ),
        migrations.DeleteModel(
            name='Group_president',
        ),
    ]
