# Generated by Django 2.2.4 on 2019-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190810_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_of_starting',
            field=models.DateField(blank=True, help_text='Дата подвешивания курса', null=True),
        ),
    ]
