# Generated by Django 2.2.4 on 2019-10-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20190829_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('knowledge', models.ForeignKey(blank=True, help_text='Курсы, которые Вы можете преподавать', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Profile_knowledge', to='core.Course')),
                ('studying', models.ForeignKey(blank=True, help_text='Курсы, которые Вы уже изучаете', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Profile_studying', to='core.Course')),
                ('teaching', models.ForeignKey(blank=True, help_text='Курсы, которые Вы уже преподаёте', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Profile_teaching', to='core.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishes', models.ForeignKey(blank=True, help_text='Курсы, которые Вы хотите изучать', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Profile_wishes', to='core.Course')),
            ],
            options={
                'unique_together': {('wishes', 'studying', 'knowledge', 'teaching')},
            },
        ),
    ]
