# Generated by Django 2.2.4 on 2019-10-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
