# Generated by Django 2.2.4 on 2019-11-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20191122_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_president',
            field=models.ForeignKey(blank=True, help_text='Староста', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_group_president', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Преподаватель курса', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('group_president', 'teacher')},
        ),
        migrations.DeleteModel(
            name='President',
        ),
    ]
