# Generated by Django 2.2.4 on 2019-11-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191124_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Другое', help_text='Название подкатегории', max_length=100)),
                ('domain', models.CharField(choices=[('Art', 'Творчество'), ('Needlework', 'Рукоделие'), ('Technical', 'Технические'), ('Medicine', 'Химбио'), ('Humanities', 'Гумаитарные'), ('Alternative', 'Другие')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Категория курса', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_teacher', to='core.Categories'),
        ),
    ]
